version: '3'

services:
        nginx:
                build:
                        context: ./mdb_httpproxy
                networks:
                        dmz:
                ports:
                        - "80:80"
                volumes:
                        - corel-10k:/data/corel_images/:ro
                depends_on:
                        - webserv
                          #                        - corel10k_fetcher
        webserv:
                build:
                        context: ./mdb_client
                networks:
                        dmz: 
                                aliases: 
                                        - "httpserv"
                        back:
                expose:
                        - "8080"
                volumes:
                        - user_picts:/app/upload/

        lire:
                image: dermotte/liresolr:latest
                networks:
                        back: 
                                aliases:
                                        - "lireserv"
                                          #        corel10k_fetcher:
                                          #                build:
                                          #                        context: ./mdb_corel10k
                                          #                volumes:
                                          #                        - corel-10k:/local/corel-10k
                                          #                depends_on:
                                          #                        - lire
                                          #                networks:
                                          #                        back:
networks:
        dmz:
        back:

volumes:
        user_picts:
        corel-10k:
