version: '3'

services:
        nginx:
                image: lfor37/mdb_httpproxy 
                networks:
                        dmz:
                ports:
                        - "80:80"
                volumes:
                        - corel-10k:/data/corel_images/:ro
                depends_on:
                        - webserv
                        - corel10k_fetcher
        webserv:
                image: lforg37/mdb_client
                networks:
                        dmz: 
                                aliases: 
                                        - "httpserv"
                        back:
                expose:
                        - "8080"
                volumes:
                        - user_picts:/app/upload/
                depends_on:
                        - database

        database:
                build:
                        context: ./mdb_database
                expose: 
                        - "1521"
                volumes:
                        - corel10k:/corel-10k/
                network:
                        back:
                                aliases:
                                        - "oraclemdb"
                depends_on:
                        - lire
                        - corel10k_fetcher
        lire:
                image: lforg37/mdb_lireapi
                networks:
                        back: 
                                aliases:
                                        - "lireserv"
                expose:
                        - "8080"
                volumes:
                        - corel-10k:/corel-10k
                        - user_picts:/app/upload
                depends_on:
                        - corel10k_fetcher
        corel10k_fetcher:
                image: lforg37/mdb_corel10k
                context: ./mdb_corel10k
                volumes:
                        - corel-10k:/install
networks:
        dmz:
        back:

volumes:
        user_picts:
        corel-10k:
