version: '2'

services:
        proxy:
                build:
                        context: ./mdb_httpproxy
                networks:
                        - dma
                ports:
                        - "80:80"
                volumes:
                        - corel-10k:/data/images/:ro
                depends_on:
                        - lire
                        - corel-10k
                        - webserv
        webserv:
                build:
                        context: ./mdb_client
                networks:
                        dma: 
                                aliases: 
                                        - "httpserv"
                        back:
                expose:
                        - "8080"
                volumes:
                        - user_picts:/tmp/images/

        lire:
                image: dermotte/liresolr:latest
                networks:
                        back: 
                                aliases:
                                        - "lireserv"
        corel-10k:
                build:
                        context: ./mdb_corel10k
                volumes:
                        - corel-10k:/local/corel-10k
                depends_on:
                        - lire
                networks:
                        back:
networks:
        dma:
        back:

volumes:
        user_picts:
        corel-10k:
