version: '3'

services:
        #        nginx:
        #                image: lforg37/mdb_httpproxy 
        #                networks:
        #                        dmz:
        #                ports:
        #                        - "25000:80"
        #                volumes:
        #                        - corel-10k:/data/corel-10k/:ro
        #                depends_on:
        #                        - webserv
        #                        - corel10k_fetcher
        webserv:
                build:
                        context: ./mdb_client
                networks:
                        dmz: 
                                aliases: 
                                        - "httpserv"
                        back:
                ports:
                        - "4242:8080"
                volumes:
                        - user_picts:/app/upload/
                        - corel-10k:/app/corel-10k/
                depends_on:
                        - database

        database:
                build:
                        context: ./mdb_database
                expose: 
                        - "1521"
                volumes:
                        - corel-10k:/corel-10k/
                networks:
                        back:
                                aliases:
                                        - "oraclemdb"
                depends_on:
                        - lire
                        - corel10k_fetcher
                privileged: true
                hostname: database
        lire:
                image: lforg37/mdb_lireapi
                networks:
                        back: 
                                aliases:
                                        - "lireserv"
                expose:
                        - "8080"
                volumes:
                        - corel-10k:/corel-10k
                        - user_picts:/app/upload/
                depends_on:
                        - corel10k_fetcher
        corel10k_fetcher:
                image: lforg37/mdb_corel10k
                volumes:
                        - corel-10k:/install
networks:
        dmz:
        back:

volumes:
        user_picts:
        corel-10k:
